import type { CatalogInstrument } from "./types";

function inst(
  symbol: string,
  name: string,
  classId: string,
  exchange = "NYSE Arca",
  kind = "etf",
): CatalogInstrument {
  return { symbol, name, classId, exchange, kind };
}

const cash: CatalogInstrument[] = [
  inst("SHY", "iShares 1-3 Year Treasury Bond ETF", "cash_equivalents"),
  inst("SHV", "iShares Short Treasury Bond ETF", "cash_equivalents"),
  inst("BIL", "SPDR Bloomberg 1-3 Month T-Bill ETF", "cash_equivalents"),
  inst("SGOV", "iShares 0-3 Month Treasury Bond ETF", "cash_equivalents"),
  inst("VGSH", "Vanguard Short-Term Treasury ETF", "cash_equivalents"),
  inst("IEI", "iShares 3-7 Year Treasury Bond ETF", "cash_equivalents"),
  inst("GBIL", "Goldman Sachs Access Treasury 0-1 Year ETF", "cash_equivalents"),
  inst("TFLO", "iShares Treasury Floating Rate Bond ETF", "cash_equivalents"),
  inst("USFR", "WisdomTree Floating Rate Treasury ETF", "cash_equivalents"),
  inst("MINT", "PIMCO Enhanced Short Maturity Active ETF", "cash_equivalents"),
  inst("NEAR", "iShares Short Maturity Bond ETF", "cash_equivalents"),
  inst("JPST", "JPMorgan Ultra-Short Income ETF", "cash_equivalents"),
  inst("ICSH", "iShares Ultra Short-Term Bond ETF", "cash_equivalents"),
  inst("FLOT", "iShares Floating Rate Bond ETF", "cash_equivalents"),
  inst("SPSB", "SPDR Portfolio Short Term Corporate Bond ETF", "cash_equivalents"),
  inst("SCHO", "Schwab Short-Term U.S. Treasury ETF", "cash_equivalents"),
  inst("SPTS", "SPDR Portfolio Short Term Treasury ETF", "cash_equivalents"),
  inst("TBIL", "US Treasury 3 Month Bill ETF", "cash_equivalents"),
  inst("FLRN", "SPDR Bloomberg Investment Grade Floating Rate ETF", "cash_equivalents"),
  inst("GSY", "Invesco Ultra Short Duration ETF", "cash_equivalents"),
  inst("FTSL", "First Trust Senior Loan Fund ETF", "cash_equivalents"),
  inst("BILS", "SPDR Bloomberg 3-12 Month T-Bill ETF", "cash_equivalents"),
  inst("CLOA", "iShares AAA CLO Active ETF", "cash_equivalents"),
  inst("CLOZ", "Panagram AAA CLO ETF", "cash_equivalents"),
  inst("SHYD", "VanEck Short High Yield Muni ETF", "cash_equivalents"),
  inst("VMOT", "Vanguard Ultra-Short-Term Bond ETF", "cash_equivalents"),
  inst("ULST", "SPDR SSgA Ultra Short Term Bond ETF", "cash_equivalents"),
  inst("CSHI", "Neuberger Berman Short Duration Income ETF", "cash_equivalents"),
  inst("JAAA", "Janus Henderson AAA CLO ETF", "cash_equivalents"),
  inst("BSCQ", "Invesco BulletShares 2026 Corporate Bond ETF", "cash_equivalents"),
];

const fiTreasury: CatalogInstrument[] = [
  inst("TLT", "iShares 20+ Year Treasury Bond ETF", "fi_treasury"),
  inst("IEF", "iShares 7-10 Year Treasury Bond ETF", "fi_treasury"),
  inst("GOVT", "iShares U.S. Treasury Bond ETF", "fi_treasury"),
  inst("VGIT", "Vanguard Intermediate-Term Treasury ETF", "fi_treasury"),
  inst("VGLT", "Vanguard Long-Term Treasury ETF", "fi_treasury"),
  inst("SCHR", "Schwab Intermediate-Term U.S. Treasury ETF", "fi_treasury"),
  inst("SCHQ", "Schwab Long-Term U.S. Treasury ETF", "fi_treasury"),
  inst("SPTL", "SPDR Portfolio Long Term Treasury ETF", "fi_treasury"),
  inst("EDV", "Vanguard Extended Duration Treasury ETF", "fi_treasury"),
  inst("ZROZ", "PIMCO 25+ Year Zero Coupon U.S. Treasury ETF", "fi_treasury"),
  inst("TLH", "iShares 10-20 Year Treasury Bond ETF", "fi_treasury"),
  inst("SPTI", "SPDR Portfolio Intermediate Term Treasury ETF", "fi_treasury"),
  inst("GOVZ", "iShares U.S. Treasury Bond ETF (Zero Coupon)", "fi_treasury"),
  inst("UTEN", "US Treasury 10 Year Note ETF", "fi_treasury"),
  inst("UTWO", "US Treasury 2 Year Note ETF", "fi_treasury"),
  inst("UTHY", "US Treasury 30 Year Bond ETF", "fi_treasury"),
  inst("TYD", "Direxion Daily 7-10 Year Treasury Bull 3X", "fi_treasury"),
  inst("TMV", "Direxion Daily 20+ Year Treasury Bear 3X", "fi_treasury"),
  inst("VGIT", "Vanguard Intermediate-Term Treasury ETF", "fi_treasury"),
  inst("SPTS", "SPDR Portfolio Short Term Treasury ETF", "fi_treasury"),
  inst("SCHO", "Schwab Short-Term U.S. Treasury ETF", "fi_treasury"),
  inst("IEI", "iShares 3-7 Year Treasury Bond ETF", "fi_treasury"),
  inst("SHY", "iShares 1-3 Year Treasury Bond ETF", "fi_treasury"),
  inst("VGSH", "Vanguard Short-Term Treasury ETF", "fi_treasury"),
  inst("BND", "Vanguard Total Bond Market ETF", "fi_treasury", "NASDAQ"),
  inst("AGG", "iShares Core U.S. Aggregate Bond ETF", "fi_treasury"),
  inst("SCHZ", "Schwab U.S. Aggregate Bond ETF", "fi_treasury"),
  inst("SPAB", "SPDR Portfolio Aggregate Bond ETF", "fi_treasury"),
  inst("VTEB", "Vanguard Tax-Exempt Bond ETF", "fi_treasury"),
  inst("SUB", "iShares Short-Term National Muni Bond ETF", "fi_treasury"),
  inst("SHM", "SPDR Nuveen Bloomberg Short Term Municipal Bond ETF", "fi_treasury"),
  inst("TFI", "SPDR Nuveen Bloomberg Municipal Bond ETF", "fi_treasury"),
  inst("PZA", "Invesco National AMT-Free Municipal Bond ETF", "fi_treasury"),
  inst("VMBS", "Vanguard Mortgage-Backed Securities ETF", "fi_treasury"),
  inst("GNMA", "iShares GNMA Bond ETF", "fi_treasury"),
  inst("SPTB", "SPDR Portfolio Treasury Bond ETF", "fi_treasury"),
];

const fiIg: CatalogInstrument[] = [
  inst("LQD", "iShares iBoxx $ Investment Grade Corporate Bond ETF", "fi_ig"),
  inst("VCIT", "Vanguard Intermediate-Term Corporate Bond ETF", "fi_ig"),
  inst("VCSH", "Vanguard Short-Term Corporate Bond ETF", "fi_ig"),
  inst("IGIB", "iShares Intermediate-Term Corporate Bond ETF", "fi_ig"),
  inst("IGSB", "iShares Short-Term Corporate Bond ETF", "fi_ig"),
  inst("SPLB", "SPDR Portfolio Long Term Corporate Bond ETF", "fi_ig"),
  inst("USIG", "iShares Broad USD Investment Grade Corporate Bond ETF", "fi_ig"),
  inst("CORP", "PIMCO Investment Grade Corporate Bond Index ETF", "fi_ig"),
  inst("LQDH", "iShares Interest Rate Hedged Corporate Bond ETF", "fi_ig"),
  inst("SCHI", "Schwab 5-10 Year Corporate Bond ETF", "fi_ig"),
  inst("GIGB", "Goldman Sachs Access Investment Grade Corporate Bond ETF", "fi_ig"),
  inst("IGLB", "iShares 10+ Year Investment Grade Corporate Bond ETF", "fi_ig"),
  inst("VCLT", "Vanguard Long-Term Corporate Bond ETF", "fi_ig"),
  inst("SPIB", "SPDR Portfolio Intermediate Term Corporate Bond ETF", "fi_ig"),
  inst("SPSB", "SPDR Portfolio Short Term Corporate Bond ETF", "fi_ig"),
  inst("FLTR", "VanEck IG Floating Rate ETF", "fi_ig"),
  inst("FLOT", "iShares Floating Rate Bond ETF", "fi_ig"),
  inst("BND", "Vanguard Total Bond Market ETF", "fi_ig", "NASDAQ"),
  inst("AGG", "iShares Core U.S. Aggregate Bond ETF", "fi_ig"),
  inst("IAGG", "iShares Core International Aggregate Bond ETF", "fi_ig"),
  inst("BNDX", "Vanguard Total International Bond ETF", "fi_ig", "NASDAQ"),
  inst("EMB", "iShares J.P. Morgan USD Emerging Markets Bond ETF", "fi_ig"),
  inst("VWOB", "Vanguard Emerging Markets Government Bond ETF", "fi_ig", "NASDAQ"),
  inst("CWB", "SPDR Bloomberg Convertible Securities ETF", "fi_ig"),
  inst("ANGL", "VanEck Fallen Angel High Yield Bond ETF", "fi_ig"),
  inst("BKLN", "Invesco Senior Loan ETF", "fi_ig"),
  inst("SRLN", "SPDR Blackstone Senior Loan ETF", "fi_ig"),
  inst("JCPB", "JPMorgan Core Plus Bond ETF", "fi_ig"),
  inst("JMBS", "Janus Henderson Mortgage-Backed Securities ETF", "fi_ig"),
  inst("MBB", "iShares MBS ETF", "fi_ig"),
];

const fiHy: CatalogInstrument[] = [
  inst("HYG", "iShares iBoxx $ High Yield Corporate Bond ETF", "fi_hy"),
  inst("JNK", "SPDR Bloomberg High Yield Bond ETF", "fi_hy"),
  inst("USHY", "iShares Broad USD High Yield Corporate Bond ETF", "fi_hy"),
  inst("SHYG", "iShares 0-5 Year High Yield Corporate Bond ETF", "fi_hy"),
  inst("HYLB", "Xtrackers USD High Yield Corporate Bond ETF", "fi_hy"),
  inst("ANGL", "VanEck Fallen Angel High Yield Bond ETF", "fi_hy"),
  inst("PHB", "Invesco Fundamental High Yield Corporate Bond ETF", "fi_hy"),
  inst("SJNK", "SPDR Bloomberg Short Term High Yield Bond ETF", "fi_hy"),
  inst("FALN", "iShares Fallen Angels USD Bond ETF", "fi_hy"),
  inst("HYGH", "iShares Interest Rate Hedged High Yield Bond ETF", "fi_hy"),
  inst("SPHY", "SPDR Portfolio High Yield Bond ETF", "fi_hy"),
  inst("HYLS", "First Trust Tactical High Yield ETF", "fi_hy"),
  inst("PGHY", "Invesco Global Short Term High Yield Bond ETF", "fi_hy"),
  inst("HYZD", "WisdomTree Interest Rate Hedged High Yield Bond ETF", "fi_hy"),
  inst("BSJK", "Invesco BulletShares 2027 High Yield Corporate Bond ETF", "fi_hy"),
  inst("BSJL", "Invesco BulletShares 2028 High Yield Corporate Bond ETF", "fi_hy"),
  inst("BSJM", "Invesco BulletShares 2029 High Yield Corporate Bond ETF", "fi_hy"),
  inst("BSJN", "Invesco BulletShares 2030 High Yield Corporate Bond ETF", "fi_hy"),
  inst("BSJO", "Invesco BulletShares 2031 High Yield Corporate Bond ETF", "fi_hy"),
  inst("HYMB", "SPDR Nuveen Bloomberg High Yield Municipal Bond ETF", "fi_hy"),
  inst("HYD", "VanEck High Yield Muni ETF", "fi_hy"),
  inst("FMHI", "First Trust Municipal High Income ETF", "fi_hy"),
  inst("HYBB", "iShares BB Rated Corporate Bond ETF", "fi_hy"),
  inst("HYS", "PIMCO 0-5 Year High Yield Corporate Bond Index ETF", "fi_hy"),
  inst("HYEM", "VanEck Emerging Markets High Yield Bond ETF", "fi_hy"),
  inst("EMHY", "iShares J.P. Morgan EM High Yield Bond ETF", "fi_hy"),
  inst("HYXU", "iShares Global ex USD High Yield Corporate Bond ETF", "fi_hy"),
  inst("SHYD", "VanEck Short High Yield Muni ETF", "fi_hy"),
  inst("HYDW", "Xtrackers Low Beta High Yield Bond ETF", "fi_hy"),
  inst("HYGV", "FlexShares High Yield Value-Scored Bond ETF", "fi_hy"),
];

const fiTips: CatalogInstrument[] = [
  inst("TIP", "iShares TIPS Bond ETF", "fi_tips"),
  inst("SCHP", "Schwab U.S. TIPS ETF", "fi_tips"),
  inst("VTIP", "Vanguard Short-Term Inflation-Protected Securities ETF", "fi_tips"),
  inst("STIP", "iShares 0-5 Year TIPS Bond ETF", "fi_tips"),
  inst("LTPZ", "PIMCO 15+ Year U.S. TIPS Index ETF", "fi_tips"),
  inst("TIPX", "SPDR Bloomberg 1-10 Year TIPS ETF", "fi_tips"),
  inst("PBTP", "Invesco 0-5 Year U.S. TIPS ETF", "fi_tips"),
  inst("GTIP", "Goldman Sachs Access Inflation Protected USD Bond ETF", "fi_tips"),
  inst("STPZ", "PIMCO 1-5 Year U.S. TIPS Index ETF", "fi_tips"),
  inst("TDTT", "FlexShares iBoxx 3-Year Target Duration TIPS ETF", "fi_tips"),
  inst("TDTF", "FlexShares iBoxx 5-Year Target Duration TIPS ETF", "fi_tips"),
  inst("IVOL", "Quadratic Interest Rate Volatility & Inflation Hedge ETF", "fi_tips"),
  inst("RINF", "ProShares Inflation Expectations ETF", "fi_tips"),
  inst("SPIP", "SPDR Portfolio TIPS ETF", "fi_tips"),
  inst("IPE", "SPDR Bloomberg Barclays TIPS ETF", "fi_tips"),
  inst("WIP", "SPDR FTSE International Government Inflation-Protected Bond ETF", "fi_tips"),
  inst("TIPZ", "PIMCO Broad U.S. TIPS Index ETF", "fi_tips"),
  inst("TIPS", "Northern Trust 2030 Inflation-Linked Distributing Ladder ETF", "fi_tips"),
  inst("TAIL", "Cambria Tail Risk ETF", "fi_tips"),
  inst("CPI", "IQ Real Return ETF", "fi_tips"),
  inst("LTPB", "iShares 10+ Year Investment Grade Corporate Bond ETF", "fi_tips"),
  inst("FIP", "FT Cboe Vest U.S. Equity Buffer ETF", "fi_tips"),
  inst("LDSF", "iShares Short Duration Bond Active ETF", "fi_tips"),
  inst("STOT", "SPDR DoubleLine Short Duration Total Return Tactical ETF", "fi_tips"),
  inst("BNDD", "Quadratic Deflation ETF", "fi_tips"),
  inst("RINF", "ProShares Inflation Expectations ETF", "fi_tips"),
  inst("FLTR", "VanEck IG Floating Rate ETF", "fi_tips"),
  inst("FLOT", "iShares Floating Rate Bond ETF", "fi_tips"),
  inst("SCHZ", "Schwab U.S. Aggregate Bond ETF", "fi_tips"),
  inst("AGG", "iShares Core U.S. Aggregate Bond ETF", "fi_tips"),
];

const fiPreferred: CatalogInstrument[] = [
  inst("PFF", "iShares Preferred and Income Securities ETF", "fi_preferred"),
  inst("PGX", "Invesco Preferred ETF", "fi_preferred"),
  inst("PFFD", "Global X U.S. Preferred ETF", "fi_preferred"),
  inst("PFFR", "InfraCap REIT Preferred ETF", "fi_preferred"),
  inst("FPE", "First Trust Preferred Securities & Income ETF", "fi_preferred"),
  inst("PSPG", "PGIM Short Duration High Yield Opportunities ETF", "fi_preferred"),
  inst("PFFA", "Virtus InfraCap U.S. Preferred Stock ETF", "fi_preferred"),
  inst("PFFV", "Global X Variable Rate Preferred ETF", "fi_preferred"),
  inst("VRDP", "Invesco Variable Rate Preferred ETF", "fi_preferred"),
  inst("SPFF", "Global X SuperIncome Preferred ETF", "fi_preferred"),
  inst("PFFL", "ETRACS 2x Leveraged Preferred Stock ETN", "fi_preferred", "NYSE", "etn"),
  inst("PREF", "Principal Spectrum Preferred Securities Active ETF", "fi_preferred"),
  inst("EPRF", "Innovator S&P Investment Grade Preferred ETF", "fi_preferred"),
  inst("JPS", "Nuveen Preferred & Income Securities Fund", "fi_preferred", "NYSE", "cef"),
  inst("PSF", "Cohen & Steers Select Preferred & Income Fund", "fi_preferred", "NYSE", "cef"),
  inst("PSK", "SPDR ICE Preferred Securities ETF", "fi_preferred"),
  inst("PFXF", "VanEck Preferred Securities ex Financials ETF", "fi_preferred"),
  inst("PGF", "Invesco Financial Preferred ETF", "fi_preferred"),
  inst("HPS", "Hancock Preferred Income Fund", "fi_preferred", "NYSE", "cef"),
  inst("HPI", "John Hancock Preferred Income Fund", "fi_preferred", "NYSE", "cef"),
  inst("HPF", "John Hancock Preferred Income Fund II", "fi_preferred", "NYSE", "cef"),
  inst("PSA", "Public Storage Preferred", "fi_preferred", "NYSE", "stock"),
  inst("ALL", "Allstate Corporation", "fi_preferred", "NYSE", "stock"),
  inst("BAC", "Bank of America Corporation", "fi_preferred", "NYSE", "stock"),
  inst("JPM", "JPMorgan Chase & Co.", "fi_preferred", "NYSE", "stock"),
  inst("WFC", "Wells Fargo & Company", "fi_preferred", "NYSE", "stock"),
  inst("MS", "Morgan Stanley", "fi_preferred", "NYSE", "stock"),
  inst("GS", "Goldman Sachs Group Inc.", "fi_preferred", "NYSE", "stock"),
  inst("C", "Citigroup Inc.", "fi_preferred", "NYSE", "stock"),
  inst("USB", "U.S. Bancorp", "fi_preferred", "NYSE", "stock"),
];

const usEquity: CatalogInstrument[] = [
  inst("SPY", "SPDR S&P 500 ETF Trust", "us_equity"),
  inst("QQQ", "Invesco QQQ Trust", "us_equity", "NASDAQ"),
  inst("IWM", "iShares Russell 2000 ETF", "us_equity"),
  inst("DIA", "SPDR Dow Jones Industrial Average ETF", "us_equity"),
  inst("IVW", "iShares S&P 500 Growth ETF", "us_equity"),
  inst("IVV", "iShares Core S&P 500 ETF", "us_equity"),
  inst("VOO", "Vanguard S&P 500 ETF", "us_equity"),
  inst("VTI", "Vanguard Total Stock Market ETF", "us_equity"),
  inst("VUG", "Vanguard Growth ETF", "us_equity"),
  inst("VTV", "Vanguard Value ETF", "us_equity"),
  inst("SCHX", "Schwab U.S. Large-Cap ETF", "us_equity"),
  inst("SCHG", "Schwab U.S. Large-Cap Growth ETF", "us_equity"),
  inst("SCHD", "Schwab U.S. Dividend Equity ETF", "us_equity"),
  inst("SPLG", "SPDR Portfolio S&P 500 ETF", "us_equity"),
  inst("ITOT", "iShares Core S&P Total U.S. Stock Market ETF", "us_equity"),
  inst("MDY", "SPDR S&P MidCap 400 ETF Trust", "us_equity"),
  inst("IJH", "iShares Core S&P Mid-Cap ETF", "us_equity"),
  inst("IJR", "iShares Core S&P Small-Cap ETF", "us_equity"),
  inst("VO", "Vanguard Mid-Cap ETF", "us_equity"),
  inst("VB", "Vanguard Small-Cap ETF", "us_equity"),
  inst("VBR", "Vanguard Small-Cap Value ETF", "us_equity"),
  inst("QUAL", "iShares MSCI USA Quality Factor ETF", "us_equity"),
  inst("USMV", "iShares MSCI USA Min Vol Factor ETF", "us_equity"),
  inst("MTUM", "iShares MSCI USA Momentum Factor ETF", "us_equity"),
  inst("RSP", "Invesco S&P 500 Equal Weight ETF", "us_equity"),
  inst("SPYG", "SPDR Portfolio S&P 500 Growth ETF", "us_equity"),
  inst("SPYV", "SPDR Portfolio S&P 500 Value ETF", "us_equity"),
  inst("AAPL", "Apple Inc.", "us_equity", "NASDAQ", "stock"),
  inst("MSFT", "Microsoft Corporation", "us_equity", "NASDAQ", "stock"),
  inst("NVDA", "NVIDIA Corporation", "us_equity", "NASDAQ", "stock"),
];

const intlEquity: CatalogInstrument[] = [
  inst("EFA", "iShares MSCI EAFE ETF", "intl_equity"),
  inst("VEA", "Vanguard FTSE Developed Markets ETF", "intl_equity"),
  inst("IEFA", "iShares Core MSCI EAFE IMI Index ETF", "intl_equity"),
  inst("IXUS", "iShares Core MSCI Total International Stock ETF", "intl_equity"),
  inst("VXUS", "Vanguard Total International Stock ETF", "intl_equity", "NASDAQ"),
  inst("SCHF", "Schwab International Equity ETF", "intl_equity"),
  inst("EFV", "iShares MSCI EAFE Value ETF", "intl_equity"),
  inst("IEUR", "iShares Core MSCI Europe ETF", "intl_equity"),
  inst("EWJ", "iShares MSCI Japan ETF", "intl_equity"),
  inst("EWG", "iShares MSCI Germany ETF", "intl_equity"),
  inst("EWU", "iShares MSCI United Kingdom ETF", "intl_equity"),
  inst("EWC", "iShares MSCI Canada ETF", "intl_equity"),
  inst("EWL", "iShares MSCI Switzerland ETF", "intl_equity"),
  inst("EWP", "iShares MSCI Spain ETF", "intl_equity"),
  inst("EWS", "iShares MSCI Singapore ETF", "intl_equity"),
  inst("EWA", "iShares MSCI Australia ETF", "intl_equity"),
  inst("EZU", "iShares MSCI Eurozone ETF", "intl_equity"),
  inst("VGK", "Vanguard FTSE Europe ETF", "intl_equity"),
  inst("EPP", "iShares MSCI Pacific ex Japan ETF", "intl_equity"),
  inst("HEFA", "iShares Currency Hedged MSCI EAFE ETF", "intl_equity"),
  inst("DBEF", "Xtrackers MSCI EAFE Hedged Equity ETF", "intl_equity"),
  inst("IEV", "iShares Europe ETF", "intl_equity"),
  inst("ACWX", "iShares MSCI ACWI ex U.S. ETF", "intl_equity"),
  inst("SPDW", "SPDR Portfolio Developed World ex-US ETF", "intl_equity"),
  inst("SCHY", "Schwab International Dividend Equity ETF", "intl_equity"),
  inst("IDV", "iShares International Select Dividend ETF", "intl_equity"),
  inst("VPL", "Vanguard FTSE Pacific ETF", "intl_equity"),
  inst("FLJP", "Franklin FTSE Japan ETF", "intl_equity"),
  inst("FLGB", "Franklin FTSE United Kingdom ETF", "intl_equity"),
  inst("BBEU", "JPMorgan BetaBuilders Europe ETF", "intl_equity"),
];

const emEquity: CatalogInstrument[] = [
  inst("EEM", "iShares MSCI Emerging Markets ETF", "em_equity"),
  inst("VWO", "Vanguard FTSE Emerging Markets ETF", "em_equity"),
  inst("IEMG", "iShares Core MSCI Emerging Markets IMI Index ETF", "em_equity"),
  inst("SCHE", "Schwab Emerging Markets Equity ETF", "em_equity"),
  inst("SPEM", "SPDR Portfolio Emerging Markets ETF", "em_equity"),
  inst("EMXC", "iShares MSCI Emerging Markets ex China ETF", "em_equity"),
  inst("EEMV", "iShares MSCI Emerging Markets Min Vol Factor ETF", "em_equity"),
  inst("GEM", "Goldman Sachs ActiveBeta Emerging Markets Equity ETF", "em_equity"),
  inst("DEM", "WisdomTree Emerging Markets High Dividend Fund", "em_equity"),
  inst("FM", "iShares MSCI Frontier and Select EM ETF", "em_equity"),
  inst("EEMS", "iShares MSCI Emerging Markets Small-Cap ETF", "em_equity"),
  inst("MCHI", "iShares MSCI China ETF", "em_equity", "NASDAQ"),
  inst("FXI", "iShares China Large-Cap ETF", "em_equity"),
  inst("EWY", "iShares MSCI South Korea ETF", "em_equity"),
  inst("EWT", "iShares MSCI Taiwan ETF", "em_equity"),
  inst("EWH", "iShares MSCI Hong Kong ETF", "em_equity"),
  inst("EWZ", "iShares MSCI Brazil ETF", "em_equity"),
  inst("EZA", "iShares MSCI South Africa ETF", "em_equity"),
  inst("INDA", "iShares MSCI India ETF", "em_equity", "BATS"),
  inst("EPHE", "iShares MSCI Philippines ETF", "em_equity"),
  inst("THD", "iShares MSCI Thailand ETF", "em_equity"),
  inst("EIDO", "iShares MSCI Indonesia ETF", "em_equity"),
  inst("ECH", "iShares MSCI Chile ETF", "em_equity"),
  inst("ARGT", "Global X MSCI Argentina ETF", "em_equity"),
  inst("EMQQ", "Emerging Markets Internet & Ecommerce ETF", "em_equity"),
  inst("VNM", "VanEck Vietnam ETF", "em_equity"),
  inst("KWEB", "KraneShares CSI China Internet ETF", "em_equity"),
  inst("ASHR", "Xtrackers Harvest CSI 300 China A-Shares ETF", "em_equity"),
  inst("EMGF", "iShares Emerging Markets Equity Factor ETF", "em_equity"),
  inst("SCHE", "Schwab Emerging Markets Equity ETF", "em_equity"),
];

const realEstate: CatalogInstrument[] = [
  inst("VNQ", "Vanguard Real Estate ETF", "real_estate"),
  inst("SCHH", "Schwab U.S. REIT ETF", "real_estate"),
  inst("IYR", "iShares U.S. Real Estate ETF", "real_estate"),
  inst("XLRE", "Real Estate Select Sector SPDR Fund", "real_estate"),
  inst("REET", "iShares Global REIT ETF", "real_estate"),
  inst("RWR", "SPDR Dow Jones REIT ETF", "real_estate"),
  inst("USRT", "iShares Core U.S. REIT ETF", "real_estate"),
  inst("VNQI", "Vanguard Global ex-U.S. Real Estate ETF", "real_estate"),
  inst("IFGL", "iShares International Developed Real Estate ETF", "real_estate"),
  inst("REM", "iShares Mortgage Real Estate ETF", "real_estate"),
  inst("MORT", "VanEck Mortgage REIT Income ETF", "real_estate"),
  inst("SRVR", "Pacer Data & Infrastructure Real Estate ETF", "real_estate"),
  inst("RWX", "SPDR Dow Jones International Real Estate ETF", "real_estate"),
  inst("FREL", "Fidelity MSCI Real Estate Index ETF", "real_estate"),
  inst("BBRE", "JPMorgan BetaBuilders MSCI U.S. REIT ETF", "real_estate"),
  inst("REZ", "iShares Residential and Multisector Real Estate ETF", "real_estate"),
  inst("HOMZ", "Hoya Capital Housing ETF", "real_estate"),
  inst("INDS", "Pacer Industrial Real Estate ETF", "real_estate"),
  inst("NETL", "NETLease Corporate Real Estate ETF", "real_estate"),
  inst("PPTY", "U.S. Diversified Real Estate ETF", "real_estate"),
  inst("PLD", "Prologis Inc.", "real_estate", "NYSE", "stock"),
  inst("AMT", "American Tower Corporation", "real_estate", "NYSE", "stock"),
  inst("EQIX", "Equinix Inc.", "real_estate", "NASDAQ", "stock"),
  inst("SPG", "Simon Property Group", "real_estate", "NYSE", "stock"),
  inst("O", "Realty Income Corporation", "real_estate", "NYSE", "stock"),
  inst("WELL", "Welltower Inc.", "real_estate", "NYSE", "stock"),
  inst("PSA", "Public Storage", "real_estate", "NYSE", "stock"),
  inst("DLR", "Digital Realty Trust", "real_estate", "NYSE", "stock"),
  inst("AVB", "AvalonBay Communities", "real_estate", "NYSE", "stock"),
  inst("EQR", "Equity Residential", "real_estate", "NYSE", "stock"),
];

const commoditiesPrecious: CatalogInstrument[] = [
  inst("GLD", "SPDR Gold Shares", "commodities_precious"),
  inst("IAU", "iShares Gold Trust", "commodities_precious"),
  inst("SLV", "iShares Silver Trust", "commodities_precious"),
  inst("SIVR", "abrdn Physical Silver Shares ETF", "commodities_precious"),
  inst("PPLT", "abrdn Physical Platinum Shares ETF", "commodities_precious"),
  inst("PALL", "abrdn Physical Palladium Shares ETF", "commodities_precious"),
  inst("GLDM", "SPDR Gold MiniShares Trust", "commodities_precious"),
  inst("SGOL", "abrdn Physical Gold Shares ETF", "commodities_precious"),
  inst("BAR", "GraniteShares Gold Trust", "commodities_precious"),
  inst("OUNZ", "VanEck Merk Gold Trust", "commodities_precious"),
  inst("GLTR", "abrdn Physical Precious Metals Basket Shares ETF", "commodities_precious"),
  inst("GDX", "VanEck Gold Miners ETF", "commodities_precious"),
  inst("GDXJ", "VanEck Junior Gold Miners ETF", "commodities_precious"),
  inst("SIL", "Global X Silver Miners ETF", "commodities_precious"),
  inst("RING", "iShares MSCI Global Gold Miners ETF", "commodities_precious"),
  inst("GOAU", "U.S. Global GO GOLD and Precious Metal Miners ETF", "commodities_precious"),
  inst("NUGT", "Direxion Daily Gold Miners Index Bull 2X Shares", "commodities_precious"),
  inst("DUST", "Direxion Daily Gold Miners Index Bear 2X Shares", "commodities_precious"),
  inst("SLVP", "iShares MSCI Global Silver and Metals Miners ETF", "commodities_precious"),
  inst("PLTM", "GraniteShares Platinum Trust", "commodities_precious"),
  inst("AAAU", "Goldman Sachs Physical Gold ETF", "commodities_precious"),
  inst("PHYS", "Sprott Physical Gold Trust", "commodities_precious", "NYSE", "trust"),
  inst("PSLV", "Sprott Physical Silver Trust", "commodities_precious", "NYSE", "trust"),
  inst("XAUUSD", "Gold Spot", "commodities_precious", "OANDA", "commodity"),
  inst("GOLD", "Barrick Gold Corporation", "commodities_precious", "NYSE", "stock"),
  inst("NEM", "Newmont Corporation", "commodities_precious", "NYSE", "stock"),
  inst("FNV", "Franco-Nevada Corporation", "commodities_precious", "NYSE", "stock"),
  inst("WPM", "Wheaton Precious Metals Corp.", "commodities_precious", "NYSE", "stock"),
  inst("RGLD", "Royal Gold Inc.", "commodities_precious", "NASDAQ", "stock"),
  inst("GDXU", "MicroSectors Gold Miners 3X Leveraged ETN", "commodities_precious", "NYSE", "etn"),
];

const commoditiesEnergy: CatalogInstrument[] = [
  inst("USO", "United States Oil Fund", "commodities_energy"),
  inst("UCO", "ProShares Ultra Bloomberg Crude Oil", "commodities_energy"),
  inst("BNO", "United States Brent Oil Fund", "commodities_energy"),
  inst("XLE", "Energy Select Sector SPDR Fund", "commodities_energy"),
  inst("VDE", "Vanguard Energy ETF", "commodities_energy"),
  inst("IYE", "iShares U.S. Energy ETF", "commodities_energy"),
  inst("OILK", "ProShares K-1 Free Crude Oil ETF", "commodities_energy"),
  inst("CRAK", "VanEck Oil Refiners ETF", "commodities_energy"),
  inst("FENY", "Fidelity MSCI Energy Index ETF", "commodities_energy"),
  inst("IEZ", "iShares U.S. Oil Equipment & Services ETF", "commodities_energy"),
  inst("XOP", "SPDR S&P Oil & Gas Exploration & Production ETF", "commodities_energy"),
  inst("PXE", "Invesco Energy Exploration & Production ETF", "commodities_energy"),
  inst("GUSH", "Direxion Daily S&P Oil & Gas Exp. & Prod. Bull 2X Shares", "commodities_energy"),
  inst("DRIP", "Direxion Daily S&P Oil & Gas Exp. & Prod. Bear 2X Shares", "commodities_energy"),
  inst("NRGU", "MicroSectors U.S. Big Oil Index 3X Leveraged ETN", "commodities_energy", "NYSE", "etn"),
  inst("UNG", "United States Natural Gas Fund", "commodities_energy"),
  inst("BOIL", "ProShares Ultra Bloomberg Natural Gas", "commodities_energy"),
  inst("KOLD", "ProShares UltraShort Bloomberg Natural Gas", "commodities_energy"),
  inst("XOM", "Exxon Mobil Corporation", "commodities_energy", "NYSE", "stock"),
  inst("CVX", "Chevron Corporation", "commodities_energy", "NYSE", "stock"),
  inst("COP", "ConocoPhillips", "commodities_energy", "NYSE", "stock"),
  inst("SLB", "Schlumberger Limited", "commodities_energy", "NYSE", "stock"),
  inst("EOG", "EOG Resources Inc.", "commodities_energy", "NYSE", "stock"),
  inst("OXY", "Occidental Petroleum", "commodities_energy", "NYSE", "stock"),
  inst("MPC", "Marathon Petroleum", "commodities_energy", "NYSE", "stock"),
  inst("VLO", "Valero Energy Corporation", "commodities_energy", "NYSE", "stock"),
  inst("PSX", "Phillips 66", "commodities_energy", "NYSE", "stock"),
  inst("HAL", "Halliburton Company", "commodities_energy", "NYSE", "stock"),
  inst("BKR", "Baker Hughes Company", "commodities_energy", "NASDAQ", "stock"),
  inst("WTI", "WTI Crude Oil Spot", "commodities_energy", "NYMEX", "commodity"),
];

const energyMlp: CatalogInstrument[] = [
  inst("AMLP", "Alerian MLP ETF", "energy_mlp"),
  inst("MLPA", "Global X MLP ETF", "energy_mlp"),
  inst("MLPX", "Global X MLP & Energy Infrastructure ETF", "energy_mlp"),
  inst("ENFR", "Alerian Energy Infrastructure ETF", "energy_mlp"),
  inst("TPYP", "Tortoise North American Pipeline Fund", "energy_mlp"),
  inst("YMLP", "VanEck High Income MLP ETF", "energy_mlp"),
  inst("EMLP", "First Trust North American Energy Infrastructure Fund", "energy_mlp"),
  inst("IMMP", "Invesco SteelPath MLP Select 40 Index ETF", "energy_mlp"),
  inst("AMZA", "InfraCap MLP ETF", "energy_mlp"),
  inst("MLPB", "ETRACS Alerian MLP Infrastructure Index ETN", "energy_mlp", "NYSE", "etn"),
  inst("PYPE", "EIP Carbon Impact MLP & Energy Transition ETF", "energy_mlp"),
  inst("FEN", "First Trust Energy Income & Growth Fund", "energy_mlp", "NYSE", "cef"),
  inst("EPD", "Enterprise Products Partners L.P.", "energy_mlp", "NYSE", "stock"),
  inst("ET", "Energy Transfer LP", "energy_mlp", "NYSE", "stock"),
  inst("MPLX", "MPLX LP", "energy_mlp", "NYSE", "stock"),
  inst("WMB", "The Williams Companies Inc.", "energy_mlp", "NYSE", "stock"),
  inst("KMI", "Kinder Morgan Inc.", "energy_mlp", "NYSE", "stock"),
  inst("OKE", "ONEOK Inc.", "energy_mlp", "NYSE", "stock"),
  inst("TRGP", "Targa Resources Corp.", "energy_mlp", "NYSE", "stock"),
  inst("PAA", "Plains All American Pipeline L.P.", "energy_mlp", "NASDAQ", "stock"),
  inst("PAGP", "Plains GP Holdings L.P.", "energy_mlp", "NASDAQ", "stock"),
  inst("SUN", "Sunoco LP", "energy_mlp", "NYSE", "stock"),
  inst("HESM", "Hess Midstream LP", "energy_mlp", "NYSE", "stock"),
  inst("DCP", "DCP Midstream LP", "energy_mlp", "NYSE", "stock"),
  inst("DTM", "DT Midstream Inc.", "energy_mlp", "NYSE", "stock"),
  inst("AM", "Antero Midstream Corporation", "energy_mlp", "NYSE", "stock"),
  inst("ENLC", "EnLink Midstream LLC", "energy_mlp", "NYSE", "stock"),
  inst("USAC", "USA Compression Partners LP", "energy_mlp", "NYSE", "stock"),
  inst("CEQP", "Crestwood Equity Partners LP", "energy_mlp", "NYSE", "stock"),
  inst("NS", "NuStar Energy L.P.", "energy_mlp", "NYSE", "stock"),
];

const healthcareBiotech: CatalogInstrument[] = [
  inst("IBB", "iShares Biotechnology ETF", "healthcare_biotech", "NASDAQ"),
  inst("XBI", "SPDR S&P Biotech ETF", "healthcare_biotech"),
  inst("BBH", "VanEck Biotech ETF", "healthcare_biotech", "NASDAQ"),
  inst("PBE", "Invesco Biotechnology & Genome ETF", "healthcare_biotech"),
  inst("FBT", "First Trust NYSE Arca Biotechnology Index Fund", "healthcare_biotech"),
  inst("SBIO", "ALPS Medical Breakthroughs ETF", "healthcare_biotech"),
  inst("LABU", "Direxion Daily S&P Biotech Bull 3X Shares", "healthcare_biotech"),
  inst("BTEC", "Principal Healthcare Innovators Index ETF", "healthcare_biotech"),
  inst("IDNA", "iShares Genomics Immunology and Healthcare ETF", "healthcare_biotech"),
  inst("GNOM", "Global X Genomics & Biotechnology ETF", "healthcare_biotech", "NASDAQ"),
  inst("XLV", "Health Care Select Sector SPDR Fund", "healthcare_biotech"),
  inst("VHT", "Vanguard Health Care ETF", "healthcare_biotech"),
  inst("IYH", "iShares U.S. Healthcare ETF", "healthcare_biotech"),
  inst("IBBJ", "Defiance Nasdaq Junior Biotechnology ETF", "healthcare_biotech", "NASDAQ"),
  inst("ARKG", "ARK Genomic Revolution ETF", "healthcare_biotech", "CBOE"),
  inst("AMGN", "Amgen Inc.", "healthcare_biotech", "NASDAQ", "stock"),
  inst("GILD", "Gilead Sciences Inc.", "healthcare_biotech", "NASDAQ", "stock"),
  inst("REGN", "Regeneron Pharmaceuticals", "healthcare_biotech", "NASDAQ", "stock"),
  inst("VRTX", "Vertex Pharmaceuticals", "healthcare_biotech", "NASDAQ", "stock"),
  inst("BIIB", "Biogen Inc.", "healthcare_biotech", "NASDAQ", "stock"),
  inst("MRNA", "Moderna Inc.", "healthcare_biotech", "NASDAQ", "stock"),
  inst("BNTX", "BioNTech SE", "healthcare_biotech", "NASDAQ", "stock"),
  inst("ILMN", "Illumina Inc.", "healthcare_biotech", "NASDAQ", "stock"),
  inst("ISRG", "Intuitive Surgical Inc.", "healthcare_biotech", "NASDAQ", "stock"),
  inst("DXCM", "DexCom Inc.", "healthcare_biotech", "NASDAQ", "stock"),
  inst("ALNY", "Alnylam Pharmaceuticals", "healthcare_biotech", "NASDAQ", "stock"),
  inst("SGEN", "Seagen Inc.", "healthcare_biotech", "NASDAQ", "stock"),
  inst("EXAS", "Exact Sciences Corporation", "healthcare_biotech", "NASDAQ", "stock"),
  inst("CRSP", "CRISPR Therapeutics AG", "healthcare_biotech", "NASDAQ", "stock"),
  inst("NTLA", "Intellia Therapeutics Inc.", "healthcare_biotech", "NASDAQ", "stock"),
];

const altBdc: CatalogInstrument[] = [
  inst("ARCC", "Ares Capital Corporation", "alt_bdc", "NASDAQ", "stock"),
  inst("MAIN", "Main Street Capital Corporation", "alt_bdc", "NYSE", "stock"),
  inst("OBDC", "Blue Owl Capital Corporation", "alt_bdc", "NYSE", "stock"),
  inst("BXSL", "Blackstone Secured Lending Fund", "alt_bdc", "NYSE", "stock"),
  inst("FSK", "FS KKR Capital Corp.", "alt_bdc", "NYSE", "stock"),
  inst("HTGC", "Hercules Capital Inc.", "alt_bdc", "NYSE", "stock"),
  inst("GBDC", "Golub Capital BDC Inc.", "alt_bdc", "NASDAQ", "stock"),
  inst("OCSL", "Oaktree Specialty Lending Corporation", "alt_bdc", "NASDAQ", "stock"),
  inst("TSLX", "Sixth Street Specialty Lending Inc.", "alt_bdc", "NYSE", "stock"),
  inst("NMFC", "New Mountain Finance Corporation", "alt_bdc", "NASDAQ", "stock"),
  inst("MFIC", "MidCap Financial Investment Corporation", "alt_bdc", "NASDAQ", "stock"),
  inst("CSWC", "Capital Southwest Corporation", "alt_bdc", "NASDAQ", "stock"),
  inst("TRIN", "Trinity Capital Inc.", "alt_bdc", "NASDAQ", "stock"),
  inst("PFLT", "PennantPark Floating Rate Capital Ltd.", "alt_bdc", "NYSE", "stock"),
  inst("TCPC", "BlackRock TCP Capital Corp.", "alt_bdc", "NASDAQ", "stock"),
  inst("SLRC", "SLR Investment Corp.", "alt_bdc", "NASDAQ", "stock"),
  inst("FDUS", "Fidus Investment Corporation", "alt_bdc", "NASDAQ", "stock"),
  inst("GSBD", "Goldman Sachs BDC Inc.", "alt_bdc", "NYSE", "stock"),
  inst("BBDC", "Barings BDC Inc.", "alt_bdc", "NYSE", "stock"),
  inst("CGBD", "Carlyle Secured Lending Inc.", "alt_bdc", "NASDAQ", "stock"),
  inst("BCSF", "Bain Capital Specialty Finance Inc.", "alt_bdc", "NYSE", "stock"),
  inst("PNNT", "PennantPark Investment Corporation", "alt_bdc", "NYSE", "stock"),
  inst("ORCC", "Owl Rock Capital Corporation", "alt_bdc", "NYSE", "stock"),
  inst("SCM", "Stellus Capital Investment Corporation", "alt_bdc", "NYSE", "stock"),
  inst("WHF", "WhiteHorse Finance Inc.", "alt_bdc", "NASDAQ", "stock"),
  inst("HRZN", "Horizon Technology Finance Corporation", "alt_bdc", "NASDAQ", "stock"),
  inst("GAIN", "Gladstone Investment Corporation", "alt_bdc", "NASDAQ", "stock"),
  inst("GLAD", "Gladstone Capital Corporation", "alt_bdc", "NASDAQ", "stock"),
  inst("TPVG", "TriplePoint Venture Growth BDC Corp.", "alt_bdc", "NYSE", "stock"),
  inst("NEWT", "NewtekOne Inc.", "alt_bdc", "NASDAQ", "stock"),
];

const altInfrastructure: CatalogInstrument[] = [
  inst("IGF", "iShares Global Infrastructure ETF", "alt_infrastructure"),
  inst("IFRA", "iShares U.S. Infrastructure ETF", "alt_infrastructure"),
  inst("TOLZ", "ProShares DJ Brookfield Global Infrastructure ETF", "alt_infrastructure"),
  inst("NFRA", "FlexShares STOXX Global Broad Infrastructure Index Fund", "alt_infrastructure"),
  inst("PAVE", "Global X U.S. Infrastructure Development ETF", "alt_infrastructure"),
  inst("GRID", "First Trust NASDAQ Clean Edge Smart Grid Infrastructure ETF", "alt_infrastructure", "NASDAQ"),
  inst("SRVR", "Pacer Data & Infrastructure Real Estate ETF", "alt_infrastructure"),
  inst("UTES", "Virtus Reaves Utilities ETF", "alt_infrastructure"),
  inst("XLU", "Utilities Select Sector SPDR Fund", "alt_infrastructure"),
  inst("VPU", "Vanguard Utilities ETF", "alt_infrastructure"),
  inst("IDU", "iShares U.S. Utilities ETF", "alt_infrastructure"),
  inst("NEE", "NextEra Energy Inc.", "alt_infrastructure", "NYSE", "stock"),
  inst("DUK", "Duke Energy Corporation", "alt_infrastructure", "NYSE", "stock"),
  inst("SO", "The Southern Company", "alt_infrastructure", "NYSE", "stock"),
  inst("D", "Dominion Energy Inc.", "alt_infrastructure", "NYSE", "stock"),
  inst("AEP", "American Electric Power", "alt_infrastructure", "NASDAQ", "stock"),
  inst("EXC", "Exelon Corporation", "alt_infrastructure", "NASDAQ", "stock"),
  inst("SRE", "Sempra", "alt_infrastructure", "NYSE", "stock"),
  inst("XEL", "Xcel Energy Inc.", "alt_infrastructure", "NASDAQ", "stock"),
  inst("WEC", "WEC Energy Group Inc.", "alt_infrastructure", "NYSE", "stock"),
  inst("ED", "Consolidated Edison Inc.", "alt_infrastructure", "NYSE", "stock"),
  inst("AWK", "American Water Works Company", "alt_infrastructure", "NYSE", "stock"),
  inst("WTRG", "Essential Utilities Inc.", "alt_infrastructure", "NYSE", "stock"),
  inst("BIP", "Brookfield Infrastructure Partners L.P.", "alt_infrastructure", "NYSE", "stock"),
  inst("BIPC", "Brookfield Infrastructure Corporation", "alt_infrastructure", "NYSE", "stock"),
  inst("CCI", "Crown Castle Inc.", "alt_infrastructure", "NYSE", "stock"),
  inst("AMT", "American Tower Corporation", "alt_infrastructure", "NYSE", "stock"),
  inst("SBAC", "SBA Communications Corporation", "alt_infrastructure", "NASDAQ", "stock"),
  inst("FTS", "Fortis Inc.", "alt_infrastructure", "NYSE", "stock"),
  inst("ENB", "Enbridge Inc.", "alt_infrastructure", "NYSE", "stock"),
];

const currencies: CatalogInstrument[] = [
  inst("UUP", "Invesco DB US Dollar Index Bullish Fund", "currencies"),
  inst("FXE", "Invesco CurrencyShares Euro Trust", "currencies"),
  inst("FXB", "Invesco CurrencyShares British Pound Sterling Trust", "currencies"),
  inst("FXY", "Invesco CurrencyShares Japanese Yen Trust", "currencies"),
  inst("FXC", "Invesco CurrencyShares Canadian Dollar Trust", "currencies"),
  inst("FXA", "Invesco CurrencyShares Australian Dollar Trust", "currencies"),
  inst("EUO", "ProShares UltraShort Euro", "currencies"),
  inst("YCL", "ProShares Ultra Yen", "currencies"),
  inst("CEW", "WisdomTree Emerging Currency Strategy Fund", "currencies"),
  inst("DBV", "Invesco DB G10 Currency Harvest Fund", "currencies"),
  inst("USDU", "WisdomTree Bloomberg U.S. Dollar Bullish Fund", "currencies"),
  inst("UDN", "Invesco DB US Dollar Index Bearish Fund", "currencies"),
  inst("CYB", "WisdomTree Chinese Yuan Strategy Fund", "currencies"),
  inst("FXF", "Invesco CurrencyShares Swiss Franc Trust", "currencies"),
  inst("FXS", "Invesco CurrencyShares Swedish Krona Trust", "currencies"),
  inst("FXM", "Invesco CurrencyShares Mexican Peso Trust", "currencies"),
  inst("BZF", "WisdomTree Brazilian Real Strategy Fund", "currencies"),
  inst("ICLN", "iShares Global Clean Energy ETF", "currencies", "NASDAQ"),
  inst("EURUSD", "Euro / US Dollar", "currencies", "OANDA", "forex"),
  inst("GBPUSD", "British Pound / US Dollar", "currencies", "OANDA", "forex"),
  inst("USDJPY", "US Dollar / Japanese Yen", "currencies", "OANDA", "forex"),
  inst("AUDUSD", "Australian Dollar / US Dollar", "currencies", "OANDA", "forex"),
  inst("USDCAD", "US Dollar / Canadian Dollar", "currencies", "OANDA", "forex"),
  inst("USDCHF", "US Dollar / Swiss Franc", "currencies", "OANDA", "forex"),
  inst("NZDUSD", "New Zealand Dollar / US Dollar", "currencies", "OANDA", "forex"),
  inst("USDMXN", "US Dollar / Mexican Peso", "currencies", "OANDA", "forex"),
  inst("USDZAR", "US Dollar / South African Rand", "currencies", "OANDA", "forex"),
  inst("USDBRL", "US Dollar / Brazilian Real", "currencies", "OANDA", "forex"),
  inst("USDTRY", "US Dollar / Turkish Lira", "currencies", "OANDA", "forex"),
  inst("USDKRW", "US Dollar / Korean Won", "currencies", "OANDA", "forex"),
];

const ALL_RAW: CatalogInstrument[] = [
  ...cash,
  ...fiTreasury,
  ...fiIg,
  ...fiHy,
  ...fiTips,
  ...fiPreferred,
  ...usEquity,
  ...intlEquity,
  ...emEquity,
  ...realEstate,
  ...commoditiesPrecious,
  ...commoditiesEnergy,
  ...energyMlp,
  ...healthcareBiotech,
  ...altBdc,
  ...altInfrastructure,
  ...currencies,
];

/** Catálogo curado — um símbolo por entrada (primeira ocorrência vence). */
export const CATALOG_INSTRUMENTS: CatalogInstrument[] = (() => {
  const seen = new Set<string>();
  const out: CatalogInstrument[] = [];
  for (const item of ALL_RAW) {
    const key = item.symbol.toUpperCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ ...item, symbol: key });
  }
  return out;
})();

export function getCatalogByClass(classId: string, limit = 30): CatalogInstrument[] {
  if (classId === "all") {
    return CATALOG_INSTRUMENTS.slice(0, limit);
  }
  return CATALOG_INSTRUMENTS.filter((i) => i.classId === classId).slice(0, limit);
}
